/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DeliveryTracking {
  'lastUpdated' : bigint,
  'orderId' : bigint,
  'driverLat' : number,
  'driverLng' : number,
  'estimatedMinutes' : bigint,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'customerPhone' : string,
  'createdAt' : bigint,
  'customerAddress' : string,
  'totalAmount' : number,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'productId' : bigint, 'quantity' : bigint }
export type OrderStatus = { 'pending' : null } |
  { 'out_for_delivery' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getDeliveryTracking' : ActorMethod<[bigint], DeliveryTracking>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, string, string], bigint>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'updateDeliveryLocation' : ActorMethod<
    [bigint, number, number, bigint],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];